# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AudioStories' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_modular_headers!

  # Pods for AudioStories
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'

  # Pods for Keyboard Manager
    pod 'IQKeyboardManagerSwift'

  # Pods for KingFisher
    pod 'Kingfisher', '~> 4.0'

  target 'AudioStoriesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AudioStoriesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
